version: '3'
services:
    web:
        image: webdevops/php-apache-dev:alpine
        container_name: web
        restart: always
        user: application
        environment:
          - WEB_ALIAS_DOMAIN=local.domain.com
          - WEB_DOCUMENT_ROOT=/app/pub
          - PHP_DATE_TIMEZONE=EST
          - PHP_DISPLAY_ERRORS=1
          - PHP_MEMORY_LIMIT=2048M
          - PHP_MAX_EXECUTION_TIME=300
          - PHP_POST_MAX_SIZE=500M
          - PHP_UPLOAD_MAX_FILESIZE=1024M
        volumes:
          - C:\Users\A696679\Desktop\Desktop\ETNA\docker_magento:/app:cached
        ports:
          - "8000:8000"
          - "443:443"
          - "32823:22"
        links:
          - mysql
    mysql:
        image: mysql/mysql-server
        container_name: mysql
        restart: always
        ports:
          - "3306:3306"
        environment:
          - MYSQL_ROOT_PASSWORD=123456789
          - MYSQL_DATABASE=mysql
        volumes:
          - db-data:/var/lib/mysql
    phpmyadmin:
        container_name: phpmyadmin
        restart: always
        image: phpmyadmin/phpmyadmin:latest
        environment:
          - MYSQL_ROOT_PASSWORD=123456789
          - PMA_USER=hatem
          - PMA_PASSWORD=password
        ports:
          - "8080:80"
        links:
          - mysql:db
        depends_on:
          - mysql
volumes:
    db-data:
        external: false
